export { default as Jumbotron } from './jumbotron/index.js';
export { default as Footer } from './footer/index.js';
export { default as Accordion } from './accordion/index.js';
export { default as Header } from './header/index.js';
export { default as OptForm } from './opt-form/index.js';
export { default as Feature } from './feature/index.js';
export { default as Form } from './form/index.js';
export { default as Profiles } from './profiles/index.js';
export { default as Loading } from './loading/index.js';